[build]
  # For static sites, we don't need a build command
  # but Netlify requires one to be set
  command = "echo 'Static site - no build needed'"
  
  # The publish directory is the root since Index.html is in the root
  publish = "."

[build.environment]
  # No special environment variables needed for static site

# Handle case-sensitive routing issues
[[redirects]]
  from = "/index.html"
  to = "/Index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/Index.html"
  status = 200